
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnpwxwtzjwkqidsunqwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucHd4d3R6andrcWlkc3VucXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjI4ODgsImV4cCI6MjA1NzkzODg4OH0.gbodScRSfWXLEEQRjNafZqSRdufQ7wvnRigP_EM2uZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a helper function to check if an error is a Supabase error
export const isSupabaseError = (error: unknown): boolean => {
  return typeof error === 'object' && 
         error !== null && 
         'code' in error && 
         'message' in error;
};
